services:
  paperless-webui:
    build:
      context: .
      dockerfile: paperlessWebUI/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - paperless-rest
  paperless-rest:
    build:
      context: . # Root des Projekts
      dockerfile: paperlessREST/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      PLUSER: ${PLUSER}
      PLUSER_PASSWORD: ${PLUSER_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    build: infra/postgres/.
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PLUSER: ${PLUSER}
      PLUSER_PASSWORD: ${PLUSER_PASSWORD}
      #POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - ./infra/postgres/pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgres-data:
  pgadmin-data:

