services:
  postgres:
    build: infra/postgres/.
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/paperless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    volumes:
      - ./infra/postgres/pgadmin-servers.json:/pgadmin4/servers.json

volumes:
  postgres-data:
  pgadmin-data:

