spring.main.web-application-type: none

# Kafka topics (input from ocr-worker, output after GenAI summarization)
kafka.topic.input.genai=${KAFKA_TOPIC_INPUT_GENAI}
kafka.topic.output.genai=${KAFKA_TOPIC_OUTPUT_GENAI}

# Kafka connection and serialization defaults (can be overridden via env vars)
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP:genai-worker}

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

google.gemini.api.key=${GOOGLE_GEMINI_API_KEY}

# OpenSearch configuration
opensearch.url=${OPENSEARCH_URL}
opensearch.index=${OPENSEARCH_INDEX}

#GOOGLE_GEMINI
google.gemini.model=${GOOGLE_GEMINI_MODEL}
google.gemini.max-rps=${GOOGLE_GEMINI_MAX_RPS}
google.gemini.max-attempts=${GOOGLE_GEMINI_MAX_ATTEMPTS}
