spring.application.name=SpringBatchDemo
# SQLite DataSource Configuration
spring.datasource.url=jdbc:sqlite:repository.sqlite
spring.datasource.driverClassName=org.sqlite.JDBC
# Spring Batch Schema Initialization
spring.batch.jdbc.initialize-schema=always

